import SwiftUI

/// A detailed panel showing input/output/cache breakdown for the
/// currently selected time window, sized to fit the popover without truncation.
struct SelectedWindowDetail: View {
    let window: TimeWindow
    let stats: UsageStats

    var body: some View {
        VStack(alignment: .leading, spacing: 8) {
            Text("\(window.displayName.uppercased()) — TOKEN BREAKDOWN")
                .font(.caption2.weight(.semibold))
                .foregroundStyle(.secondary)

            // 2x2 grid keeps every label fully visible.
            Grid(alignment: .leading, horizontalSpacing: 16, verticalSpacing: 4) {
                GridRow {
                    metric(color: .blue,
                           label: "Input",
                           value: Formatters.compactInt(stats.inputTokens),
                           help: "Total prompt tokens sent to the model (includes cache reads). Source: session-shutdown summaries.")
                    metric(color: .green,
                           label: "Output",
                           value: Formatters.compactInt(stats.outputTokens),
                           help: "Total tokens generated by the model.")
                }
                GridRow {
                    metric(color: .purple,
                           label: "Cache read",
                           value: Formatters.compactInt(stats.cacheReadTokens),
                           help: "Tokens that were served from prompt cache (the 'hits').")
                    metric(color: .indigo,
                           label: "Cache write",
                           value: Formatters.compactInt(stats.cacheWriteTokens),
                           help: "Tokens written to prompt cache for future re-use.")
                }
            }

            CacheHitBar(stats: stats)
            CostEstimateRow(stats: stats)
        }
    }

    private func metric(color: Color, label: String, value: String, help: String) -> some View {
        HStack(alignment: .firstTextBaseline, spacing: 6) {
            Circle().fill(color).frame(width: 7, height: 7)
            Text(label)
                .font(.system(size: 11))
                .foregroundStyle(.secondary)
            Spacer(minLength: 0)
            Text(value)
                .font(.system(size: 12, weight: .semibold, design: .rounded))
                .monospacedDigit()
        }
        .help(help)
    }
}

/// Horizontal stacked bar visualizing prompt-cache hit rate:
///   purple slice  = cache reads  (the hit)
///   gray slice    = fresh input  (the miss)
private struct CacheHitBar: View {
    let stats: UsageStats

    var body: some View {
        if let rate = stats.cacheHitRate {
            VStack(alignment: .leading, spacing: 4) {
                HStack(spacing: 6) {
                    Image(systemName: "memorychip")
                        .font(.system(size: 10))
                        .foregroundStyle(.purple)
                    Text("Cache hit rate")
                        .font(.caption2)
                        .foregroundStyle(.secondary)
                    Spacer()
                    Text(String(format: "%.1f%%", rate * 100))
                        .font(.system(size: 12, weight: .semibold, design: .rounded))
                        .monospacedDigit()
                        .foregroundStyle(rate >= 0.8 ? .green : (rate >= 0.5 ? .orange : .red))
                }
                .help("\(Formatters.compactInt(stats.cacheReadTokens)) cached + \(Formatters.compactInt(stats.freshInputTokens)) fresh = \(Formatters.compactInt(stats.inputTokens)) input tokens. Higher is better — fewer tokens billed at full rate.")
                GeometryReader { geo in
                    HStack(spacing: 1) {
                        RoundedRectangle(cornerRadius: 2)
                            .fill(LinearGradient(
                                colors: [.purple, .purple.opacity(0.7)],
                                startPoint: .leading, endPoint: .trailing
                            ))
                            .frame(width: max(2, geo.size.width * CGFloat(rate)))
                        RoundedRectangle(cornerRadius: 2)
                            .fill(Color.secondary.opacity(0.25))
                    }
                }
                .frame(height: 6)
                HStack(spacing: 12) {
                    Label("\(Formatters.compactInt(stats.cacheReadTokens)) hit", systemImage: "checkmark.circle.fill")
                        .labelStyle(.titleAndIcon)
                        .font(.system(size: 10))
                        .foregroundStyle(.purple)
                    Label("\(Formatters.compactInt(stats.freshInputTokens)) miss", systemImage: "circle")
                        .labelStyle(.titleAndIcon)
                        .font(.system(size: 10))
                        .foregroundStyle(.secondary)
                    if stats.cacheWriteTokens > 0 {
                        Label("\(Formatters.compactInt(stats.cacheWriteTokens)) written", systemImage: "arrow.down.to.line")
                            .labelStyle(.titleAndIcon)
                            .font(.system(size: 10))
                            .foregroundStyle(.indigo)
                            .help("Tokens written to cache for future re-use (counted as misses for THIS request but accelerate later ones).")
                    }
                    Spacer()
                }
            }
        }
    }
}
